### PR TITLE
Add PyLadies Recife local logo

### PR DESCRIPTION
**Pull request by cecivieira**
Add a new logo for our specific location (Recife-Brazil).

### CODE REVIEW

**Comment by cecivieira** [comment]
@lorenanicole Hi!!! Could you approve this logo?

**Comment by Mariatta** [comment]
The changeset contains tons of other changes, not just a new logo.

Are the other changes necessary? Or perhaps the branch is out of date with master branch?

**Comment by lorenanicole** [comment]
Ah yes, I agree with @Mariatta . As you can see below there's approximately 43 files changed:

image

Can you please rebase your branch with master so we only have the one file added: `locations/Recife-BR/pyladies_recife_logo.svg`?  Thanks!

**Comment by cecivieira** [comment]
Sorry!!!
I'm closing this pull request and will open the correct one.

**Pull request closed without merging**
